export enum MenuLocationEnum {
  LOGGEDIN_ACCOUNT_MENU = "LOGGEDIN_ACCOUNT_MENU",
  FOOTER_MENU = "FOOTER_MENU",
  MOBILE_MENU = "MOBILE_MENU",
  PRIMARY = "PRIMARY",
  SECONDARY_MENU = "SECONDARY_MENU",
}
