export enum PageGroupEnvKeyEnum {
  FRONT_PAGE = "FRONT_PAGE",
  BOOKING = "BOOKING",
  TICKET_DETAIL = "TICKET_DETAIL",
  BLOG = "BLOG",
  PROFILE = "PROFILE",
  CONFIRM_EMAIL = "CONFIRM_EMAIL",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  SCHEDULES = "SCHEDULES",
  SIGN_IN = "SIGN_IN",
  SIGN_UP = "SIGN_UP",
  USER_BOOKINGS = "USER_BOOKINGS",
  PASSWORD_CHANGE = "PASSWORD_CHANGE",
  PAYMENT = "PAYMENT",

  TERM_CONDITION = "TERM_CONDITION",

  TRANSACTIONS = "TRANSACTIONS",
  USER_CANCEL_TICKET_REQUEST = "USER_CANCEL_TICKET_REQUEST",
}
