export enum PageStatus {
  PUBLISH = "PUBLISH",
  FUTURE = "FUTURE",
  DRAFT = "DRAFT",
  PENDING = "PENDING",
  PRIVATE = "PRIVATE",
  TRASH = "TRASH",
  AUTO_DRAFT = "AUTO_DRAFT",
  INHERIT = "INHERIT",
  REQUEST_COMPLETED = "REQUEST_COMPLETED",
  REQUEST_FAILED = "REQUEST_FAILED",

  REQUEST_CONFIRMED = "REQUEST_CONFIRMED",
  REQUEST_PENDING = "REQUEST_PENDING",

  ACF_DISABLED = "ACF_DISABLED",
}
