export const provinceCCCD = [
  { oldName: "Hà Nội", code: "001", name: "Hà Nội" },
  { oldName: "Hà Giang", code: "002", name: "Tuyên Quang" },
  { oldName: "Cao Bằng", code: "004", name: "Cao Bằng" },
  { oldName: "Bắc Kạn", code: "006", name: "Thái nguyên" },
  { oldName: "Tuyên Quang", code: "008", name: "Tuyên Quang" },
  { oldName: "Lào Cai", code: "010", name: "Lào Cai" },
  { oldName: "Điện Biên", code: "011", name: "Điện Biên" },
  { oldName: "Lai Châu", code: "012", name: "Lai Châu" },
  { oldName: "Sơn La", code: "014", name: "Sơn La" },
  { oldName: "Yên Bái", code: "015", name: "Lào Cai" },
  { oldName: "Hòa Bình", code: "017", name: "Phú Thọ" },
  { oldName: "Thái Nguyên", code: "019", name: "Thái Nguyên" },
  { oldName: "Lạng Sơn", code: "020", name: "Lạng Sơn" },
  { oldName: "Quảng Ninh", code: "022", name: "Quảng Ninh" },
  { oldName: "Bắc Giang", code: "024", name: "Bắc Ninh" },
  { oldName: "Phú Thọ", code: "025", name: "Phú Thọ" },
  { oldName: "Vĩnh Phúc", code: "026", name: "Phú Thọ" },
  { oldName: "Bắc Ninh", code: "027", name: "Bắc Ninh" },
  { oldName: "Hải Dương", code: "030", name: "Hải Phòng" },
  { oldName: "Hải Phòng", code: "031", name: "Hải Phòng" },
  { oldName: "Hưng Yên", code: "033", name: "Hưng Yên" },
  { oldName: "Thái Bình", code: "034", name: "Hưng Yên" },
  { oldName: "Hà Nam", code: "035", name: "Ninh Bình" },
  { oldName: "Nam Định", code: "036", name: "Ninh Bình" },
  { oldName: "Ninh Bình", code: "037", name: "Ninh Bình" },
  { oldName: "Thanh Hóa", code: "038", name: "Thanh Hóa" },
  { oldName: "Nghệ An", code: "040", name: "Nghệ An" },
  { oldName: "Hà Tĩnh", code: "042", name: "Hà Tĩnh" },
  { oldName: "Quảng Bình", code: "044", name: "Quảng Trị" },
  { oldName: "Quảng Trị", code: "045", name: "Quảng Trị" },
  { oldName: "Thừa Thiên Huế", code: "046", name: "Thừa Thiên Huế" },
  { oldName: "Đà Nẵng", code: "048", name: "Đà Nẵng" },
  { oldName: "Quảng Nam", code: "049", name: "Đà Nẵng" },
  { oldName: "Quảng Ngãi", code: "051", name: "Quảng Ngãi" },
  { oldName: "Bình Định", code: "052", name: "Gia Lai" },
  { oldName: "Phú Yên", code: "054", name: "Đắk Lắk" },
  { oldName: "Khánh Hòa", code: "056", name: "Khánh Hòa" },
  { oldName: "Ninh Thuận", code: "058", name: "Khánh Hòa" },
  { oldName: "Bình Thuận", code: "060", name: "Lâm Đồng" },
  { oldName: "Kon Tum", code: "062", name: "Quảng Ngãi" },
  { oldName: "Gia Lai", code: "064", name: "Gia Lai" },
  { oldName: "Đắk Lắk", code: "066", name: "Đắk Lắk" },
  { oldName: "Đắk Nông", code: "067", name: "Lâm Đồng" },
  { oldName: "Lâm Đồng", code: "068", name: "Lâm Đồng" },
  { oldName: "Bình Phước", code: "070", name: "Đồng Nai" },
  { oldName: "Tây Ninh", code: "072", name: "Tây Ninh" },
  { oldName: "Bình Dương", code: "074", name: "Hồ Chí Minh" },
  { oldName: "Đồng Nai", code: "075", name: "Đồng Nai" },
  { oldName: "Bà Rịa - Vũng Tàu", code: "077", name: "Hồ Chí Minh" },
  { oldName: "Hồ Chí Minh", code: "079", name: "Hồ Chí Minh" },
  { oldName: "Long An", code: "080", name: "Tây Ninh" },
  { oldName: "Tiền Giang", code: "082", name: "Đồng Tháp" },
  { oldName: "Bến Tre", code: "083", name: "Vĩnh Long" },
  { oldName: "Trà Vinh", code: "084", name: "Vĩnh Long" },
  { oldName: "Vĩnh Long", code: "086", name: "Vĩnh Long" },
  { oldName: "Đồng Tháp", code: "087", name: "Đồng Tháp" },
  { oldName: "An Giang", code: "089", name: "An Giang" },
  { oldName: "Kiên Giang", code: "091", name: "An Giang" },
  { oldName: "Cần Thơ", code: "092", name: "Cần Thơ" },
  { oldName: "Hậu Giang", code: "093", name: "Cần Thơ" },
  { oldName: "Sóc Trăng", code: "094", name: "Cần Thơ" },
  { oldName: "Bạc Liêu", code: "095", name: "Cà Mau" },
  { oldName: "Cà Mau", code: "096", name: "Cà Mau" },
];

export function getProvinceByCCCD(cccd: string) {
  if (cccd) {
    return provinceCCCD.find((province) => province.code === cccd.slice(0, 3));
  }
  return null;
}
