// Tour/Product queries
export {
  GET_ALL_TOURS,
  GET_ALL_TOUR_SLUGS,
  GET_TOUR_BY_SLUG,
  GET_TOURS_BY_DESTINATION,
  GET_TOURS_BY_TRAVEL_STYLE,
  GET_TOURS_BY_TOUR_TYPE,
  GET_TOURS_BY_TAG,
  GET_TOURS_BY_COMBINED_FILTERS,
} from "./tours";

// Taxonomy queries
export {
  GET_ALL_DESTINATIONS,
  GET_ALL_DESTINATIONS_FLAT,
  GET_DESTINATION_BY_SLUG,
  GET_ALL_TOUR_TYPES,
  GET_ALL_TRAVEL_STYLES,
  GET_ALL_PRODUCT_TAGS,
  GET_TOUR_FILTER_OPTIONS,
} from "./taxonomies";

// Blog & News queries
export {
  GET_ALL_BLOG_POSTS,
  GET_ALL_POST_SLUGS,
  GET_ALL_POST_CATEGORIES,
  GET_POST_BY_SLUG,
  GET_ALL_NEWS,
  GET_NEWS_BY_SUBCATEGORY,
  GET_NEWS_BY_SLUG,
} from "./blog";

// Site-wide queries
export {
  GET_SITE_SETTINGS,
  GET_LAYOUT_DATA,
  GET_ALL_MENUS,
  GET_MENU_BY_LOCATION,
  GET_ALL_PAGES,
  GET_PAGE_BY_SLUG,
  GET_ALL_PAGE_SLUGS,
  GET_TOUR_CONSTANT,
} from "./site";
