export type TaxRecord = {
  activeStatus: string;
  status: string;
  modifiedDate: string;
  taxCode: string;
  companyName: string;
  shortName: string;
  businessResistration: string | null;
  registedDate: string;
  registedLocation: string | null;
  foundedDate: string;
  companyType: string | null;
  businessType: string;
  fax: string;
  website: string;
  email: string;
  owner: string;
  ownerPosition: string;
  ownerPhoneNumber: string;
  ownerEmail: string;
  address: string;
  province: string;
  district: string;
  ward: string;
  contactEmail: string;
  contactPhoneNumber: string;
};
